
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '..');

function parseFrontmatter(content) {
    const match = content.match(/^---\n([\s\S]*?)\n---\n/);
    if (!match) return {};
    const rawFm = match[1];
    const data = {};
    rawFm.split('\n').forEach(line => {
        const parts = line.split(':');
        if (parts.length >= 2) {
            data[parts[0].trim()] = parts.slice(1).join(':').trim().replace(/^"(.*)"$/, '$1');
        }
    });
    return data;
}

function generateIndex({ itemsDir, outputFile, lang, title, intro, glossaryTitle, qaTitle, categoryTitles }) {
    let output = `# ${title}\n\n`;
    output += `> ${intro}\n\n`;
    output += `${lang === 'zh' ? '最後更新時間' : 'Last Updated'}：${new Date().toLocaleString(lang === 'zh' ? 'zh-TW' : 'en-US', { timeZone: 'Asia/Taipei' })}\n\n`;

    // 1. Glossary
    output += `## ${glossaryTitle}\n\n`;
    const glossaryDir = path.join(itemsDir, 'glossary');
    if (fs.existsSync(glossaryDir)) {
        const files = fs.readdirSync(glossaryDir).filter(f => f.endsWith('.md')).sort();
        output += `${lang === 'zh' ? '目前共有' : 'Total'} **${files.length}** ${lang === 'zh' ? '個術語' : 'terms'}：\n\n`;
        files.forEach(file => {
            const content = fs.readFileSync(path.join(glossaryDir, file), 'utf-8');
            const data = parseFrontmatter(content);
            output += `- **${data.term || file}** (\`${file}\`)\n`;
        });
    }
    output += `\n---\n\n`;

    // 2. Q&A
    output += `## ${qaTitle}\n\n`;
    const qaOrder = ['account', 'enrollment', 'apps', 'classroom', 'digital-learning', 'hardware', 'mac', 'qa-education'];

    qaOrder.forEach(category => {
        const categoryDir = path.join(itemsDir, 'qa', category);
        if (fs.existsSync(categoryDir)) {
            output += `### ${categoryTitles[category] || category} (\`qa/${category}\`)\n\n`;
            const files = fs.readdirSync(categoryDir).filter(f => f.endsWith('.md')).sort((a, b) => {
                return a.localeCompare(b, undefined, { numeric: true });
            });
            files.forEach(file => {
                try {
                    const content = fs.readFileSync(path.join(categoryDir, file), 'utf-8');
                    const data = parseFrontmatter(content);
                    output += `- [\`${data.id || 'N/A'}\`] ${data.title || file}\n`;
                } catch (e) {
                    output += `- [\`ERROR\`] ${file}\n`;
                }
            });
            output += `\n`;
        }
    });

    fs.writeFileSync(outputFile, output, 'utf-8');
    console.log(`[Index Generator] Index updated at ${outputFile}`);
}

// 產生中文版
generateIndex({
    itemsDir: path.join(ROOT, 'docs', 'data', 'items'),
    outputFile: path.join(ROOT, 'docs', 'data', 'MAINTENANCE_INDEX.md'),
    lang: 'zh',
    title: '維護索引 (Maintenance Index)',
    intro: '此文件由腳本自動生成。用於讓維護人員（或 AI）快速確認目前已存在的內容，避免重複新增。',
    glossaryTitle: '術語表 (Glossary)',
    qaTitle: '問答集 (Q&A)',
    categoryTitles: {
        'account': '帳號與伺服器',
        'enrollment': '裝置註冊',
        'apps': 'App 管理',
        'classroom': '課堂管理',
        'digital-learning': '數位精進',
        'hardware': '硬體排除',
        'mac': 'Mac 管理',
        'qa-education': '教育實戰'
    }
});

// 產生英文版
generateIndex({
    itemsDir: path.join(ROOT, 'docs', 'data', 'items-en'),
    outputFile: path.join(ROOT, 'docs', 'data', 'MAINTENANCE_INDEX_EN.md'),
    lang: 'en',
    title: 'Maintenance Index (EN Version)',
    intro: 'This file is automatically generated for maintainers (or AI) to quickly check existing English content and avoid duplicates.',
    glossaryTitle: 'Glossary (EN)',
    qaTitle: 'Q&A (EN)',
    categoryTitles: {
        'account': 'Account & Server',
        'enrollment': 'Enrollment',
        'apps': 'Apps & Content',
        'classroom': 'Classroom Tools',
        'digital-learning': 'Digital Initiatives',
        'hardware': 'Hardware Tuning',
        'mac': 'Mac Management',
        'qa-education': 'Education Scenarios'
    }
});
